language: html
html:
        - html3
        - html4
        - html5
cash: yarn

install:
        - yarn install

script:
        - yarn test
        - yarn run build

deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: build
        ON:
            branch: master
           

 
